### ISSUE TITLE
'Open in ID' button in safari always opens same location

### ISSUE THREAD

**Issue by harry-wood** [osmlab/maproulette#354]
The "Open in ID" button is not working for me in Safari. Regardless of which challenge I'm on it always opens at the same wrong location in the chinatown district of DC at a URL like this: https://openstreetmap.us/iD/release/#background=Bing&map=20.00/-77.02271/38.90085

I don't know if this a bug in MapRoulette or in the openstreetmap.us/iD instance.

works fine in Chrome.

**Comment by mvexel** [comment]
I think this is fixed now with my latest update, but please verify!

**Comment by harry-wood** [comment]
no. I'm seeing the same problem still.   ...although safari's ever-unflushable cache could be playing tricks on me now :-(

**Comment by mvexel** [comment]
Do you know about the Develop menu? You can disable caches there.
